using System.Numerics;
using System.Threading.Channels;
using Resonalyze.Dsp;
using Resonalyze.Options;

namespace Resonalyze
{
    /// <summary>Live transfer-function / RTA analysis of captured noise; the streaming lifecycle lives behind <see cref="IAudioStreamingSession"/>.</summary>
    public sealed class NoiseMeasurement : IDisposable
    {
        private readonly IAudioSessionFactory audioSessionFactory;
        private readonly object stateSync = new();
        private readonly object dataSync = new();
        private CancellationTokenSource? cancellationTokenSource;
        private Task<bool>? measurementTask;
        private ChannelWriter<float[][]>? sequenceWriter;
        private Complex[]? accumulatedCrossSpectrum;
        private double[]? accumulatedReferencePowerSpectrum;
        private double[]? accumulatedTargetPowerSpectrum;
        private double transferAlpha = 1.0;
        private bool infiniteAveraging;
        private int averagedFrameCount;
        private int clippedFrameCount;
        private int sequencesCounter;
        private long lastDropTickMs;
        private int droppedFrameTotal;
        private volatile int captureMicrophoneIndex;
        private volatile int captureLoopbackIndex = -1;
        // Bumped per dropped block so the loop resets the reframer and never builds a frame across the gap.
        private long dropGeneration;
        // Fewer EMA frames read gamma^2 near 1 regardless of the channel relation.
        private const int MinCoherenceFrames = 4;
        private AveragingSpeed appliedAveragingSpeed;
        private volatile bool inProgress;
        private bool disposed;
        private double playbackDuration = 60.0;

        public event Action<bool>? Completed;
        internal event Action<InputLevelMeterSnapshot>? LevelsAvailable;

        private NoiseSignal? signal;

        public NoiseMeasurement(IAudioSessionFactory audioSessionFactory)
        {
            this.audioSessionFactory = audioSessionFactory ??
                throw new ArgumentNullException(nameof(audioSessionFactory));
        }

        public bool InProgress => inProgress;
        public int SampleRate { get; private set; }

        /// <summary>Regenerated by <see cref="Init"/>; without an SPL anchor, spatial-average captures share one level offset only within one id (hardware gain changes are invisible to it).</summary>
        public Guid CaptureSessionId { get; private set; } = Guid.NewGuid();

        /// <summary>Protective high-pass frozen at run start for this accumulation. See docs/tech/sweep-measurement.md#live-capture-snapshots.</summary>
        public ProtectiveHighPassConfiguration CaptureProtectiveHighPass
        {
            get;
            private set;
        } = ProtectiveHighPassConfiguration.Off;

        /// <summary>Called right before <see cref="RunAsync"/>, the only moment the filter may change.</summary>
        public void SetCaptureProtectiveHighPass(
            ProtectiveHighPassConfiguration? protectiveHighPass) =>
            CaptureProtectiveHighPass =
                ProtectiveHighPassConfiguration.Normalize(protectiveHighPass);

        /// <summary>Mic calibration curve frozen at run start (curve, not id, so later edits cannot reach the capture).</summary>
        public CalibrationFile? CaptureMicrophoneCalibration { get; private set; }

        /// <summary>Calibration list name at run start; people read it, ids are for matching.</summary>
        public string CaptureMicrophoneCalibrationName { get; private set; } = string.Empty;

        public string? CaptureMicrophoneCalibrationId { get; private set; }

        public void SetCaptureMicrophoneCalibration(CapturedMicrophoneCalibration calibration)
        {
            ArgumentNullException.ThrowIfNull(calibration);
            CaptureMicrophoneCalibrationId = calibration.Id;
            CaptureMicrophoneCalibrationName = calibration.Name;
            CaptureMicrophoneCalibration = calibration.Curve;
        }

        public int AveragedFrameCount
        {
            get
            {
                lock (dataSync)
                {
                    return averagedFrameCount;
                }
            }
        }
        public int Bits { get; private set; }
        public PlaybackChannel PlaybackChannel { get; private set; }
        public AudioBackend AudioBackend { get; private set; } = AudioBackend.Wave;
        public int OutputDeviceNumber { get; private set; } = -1;
        public int InputDeviceNumber { get; private set; } = -1;
        public string? WasapiCaptureEndpointId { get; private set; }
        public string? WasapiRenderEndpointId { get; private set; }
        public int WasapiBufferMilliseconds { get; private set; } = 100;
        public string? AsioDriverName { get; private set; }
        public int AsioInputChannelOffset { get; private set; }
        public int? AsioLoopbackInputChannelOffset { get; private set; }
        public int AsioOutputChannelOffset { get; private set; }
        public int WaveInputChannelOffset { get; private set; }
        public int? WaveLoopbackInputChannelOffset { get; private set; }
        public int SequenceLength { get; private set; }
        public LiveSpectrumOptions LiveSpectrumOptions { get; private set; } = new();
        public Exception? LastError { get; private set; }
        public bool HasConfiguredLoopback =>
            AudioBackend == AudioBackend.Asio
                ? AsioLoopbackInputChannelOffset.HasValue &&
                    AsioLoopbackInputChannelOffset.Value != AsioInputChannelOffset
                : WaveLoopbackInputChannelOffset.HasValue &&
                    WaveLoopbackInputChannelOffset.Value != WaveInputChannelOffset;

        /// <summary>No loopback configured: single-channel RTA (auto-power only, no transfer or coherence).</summary>
        public bool IsMicOnly => !HasConfiguredLoopback;

        // Cannot flip mid-run: Silent is RTA-exclusive and a mode change restarts the capture.
        public bool IsRtaCapture =>
            IsMicOnly || LiveSpectrumOptions.AnalysisMode.IsReferenceFree();

        /// <summary>Mic input identity for validating an SPL anchor, mapped like the sweep (device number only for Wave).</summary>
        public MeasurementInputIdentity CurrentInputIdentity() => new(
            AudioBackend,
            SampleRate,
            Bits,
            AudioBackend == AudioBackend.Asio ? AsioInputChannelOffset : WaveInputChannelOffset,
            AudioBackend == AudioBackend.Wave ? InputDeviceNumber : null,
            WasapiCaptureEndpointId,
            AsioDriverName);

        public void Init(
            int sampleRate,
            int bits,
            double requestedDuration,
            PlaybackChannel playbackChannel,
            int sequenceLength = 2048,
            int outputDeviceNumber = -1,
            int inputDeviceNumber = -1,
            AudioBackend audioBackend = AudioBackend.Wave,
            string? asioDriverName = null,
            int asioInputChannelOffset = 0,
            int asioOutputChannelOffset = 0,
            int waveInputChannelOffset = 0,
            int? waveLoopbackInputChannelOffset = null,
            int? asioLoopbackInputChannelOffset = null,
            LiveSpectrumOptions? liveSpectrumOptions = null,
            string? wasapiCaptureEndpointId = null,
            string? wasapiRenderEndpointId = null,
            int wasapiBufferMilliseconds = 100)
        {
            ThrowIfDisposed();
            if (InProgress)
            {
                throw new InvalidOperationException("Cannot reinitialize an active measurement.");
            }
            if (sequenceLength < 2)
            {
                throw new ArgumentOutOfRangeException(nameof(sequenceLength));
            }

            CaptureSessionId = Guid.NewGuid();
            SequenceLength = sequenceLength;
            PlaybackChannel = playbackChannel;
            SampleRate = sampleRate;
            Bits = bits;
            OutputDeviceNumber = outputDeviceNumber;
            InputDeviceNumber = inputDeviceNumber;
            AudioBackend = audioBackend;
            WasapiCaptureEndpointId = wasapiCaptureEndpointId;
            WasapiRenderEndpointId = wasapiRenderEndpointId;
            WasapiBufferMilliseconds = Math.Clamp(wasapiBufferMilliseconds, 10, 100);
            AsioDriverName = asioDriverName;
            AsioInputChannelOffset = asioInputChannelOffset;
            AsioLoopbackInputChannelOffset = asioLoopbackInputChannelOffset;
            AsioOutputChannelOffset = asioOutputChannelOffset;
            int normalizedWaveInputChannelOffset = audioBackend.IsWasapi()
                ? Math.Max(0, waveInputChannelOffset)
                : Math.Clamp(waveInputChannelOffset, 0, 1);
            int? normalizedWaveLoopbackInputChannelOffset = audioBackend.IsWasapi()
                ? NormalizeOptionalWasapiChannel(waveLoopbackInputChannelOffset)
                : NormalizeOptionalWaveChannel(waveLoopbackInputChannelOffset);
            if (audioBackend != AudioBackend.Asio &&
                normalizedWaveLoopbackInputChannelOffset == normalizedWaveInputChannelOffset)
            {
                throw new InvalidOperationException(
                    "Microphone and loopback inputs must use different channels.");
            }
            WaveInputChannelOffset = normalizedWaveInputChannelOffset;
            WaveLoopbackInputChannelOffset = normalizedWaveLoopbackInputChannelOffset;
            LiveSpectrumOptions = liveSpectrumOptions ?? new LiveSpectrumOptions();
            playbackDuration = requestedDuration;

            RefreshPlaybackSignal();
        }

        public void RefreshPlaybackSignal()
        {
            ThrowIfDisposed();
            if (InProgress)
            {
                throw new InvalidOperationException(
                    "Cannot replace the playback signal during an active measurement.");
            }

            signal?.Dispose();
            signal = new NoiseSignal();
            // Periodic pink loops one FFT period seamlessly; the full duration would allocate ~35 MB LOH at start. Aperiodic noise seams in a short loop.
            double signalDuration =
                EffectiveNoiseColor is NoiseColor.PinkPeriodic or NoiseColor.Silent
                    ? SequenceLength / (double)SampleRate
                    : playbackDuration;
            signal.FillData(
                signalDuration,
                Bits,
                SampleRate,
                EffectiveNoiseColor,
                SequenceLength);
        }

        public Task<bool> RunAsync()
        {
            ThrowIfDisposed();
            lock (stateSync)
            {
                if (measurementTask is { IsCompleted: false })
                {
                    return measurementTask;
                }
                if (signal == null)
                {
                    throw new InvalidOperationException("Measurement is not initialized.");
                }

                lock (dataSync)
                {
                    accumulatedCrossSpectrum = null;
                    accumulatedReferencePowerSpectrum = null;
                    accumulatedTargetPowerSpectrum = null;
                    sequencesCounter = 0;
                    averagedFrameCount = 0;
                    clippedFrameCount = 0;
                }
                Interlocked.Exchange(ref lastDropTickMs, 0);
                Interlocked.Exchange(ref droppedFrameTotal, 0);

                cancellationTokenSource?.Dispose();
                cancellationTokenSource = new CancellationTokenSource();
                inProgress = true;
                LastError = null;
                measurementTask = RunCoreAsync(cancellationTokenSource.Token);
                return measurementTask;
            }
        }

        public async Task AbortAsync()
        {
            Task<bool>? runningTask;
            lock (stateSync)
            {
                cancellationTokenSource?.Cancel();
                runningTask = measurementTask;
            }

            if (runningTask != null)
            {
                try
                {
                    await runningTask.ConfigureAwait(false);
                }
                catch (OperationCanceledException)
                {
                }
            }
        }

        /// <summary>Clones accumulators under the lock and runs the math outside it, so a slow UI cannot stall accumulation.</summary>
        public LiveSpectrumSnapshot? GetAccumulatedSpectrumSnapshot(
            bool includeInputMagnitude = true)
        {
            Complex[]? crossSpectrum;
            double[]? referencePowerSpectrum;
            double[] targetPowerSpectrum;
            int frameCount;
            int clippedFrames;
            double coherenceNoiseFloor;
            lock (dataSync)
            {
                if (accumulatedTargetPowerSpectrum == null)
                {
                    return null;
                }

                targetPowerSpectrum = (double[])accumulatedTargetPowerSpectrum.Clone();
                crossSpectrum = accumulatedCrossSpectrum != null
                    ? (Complex[])accumulatedCrossSpectrum.Clone()
                    : null;
                referencePowerSpectrum = accumulatedReferencePowerSpectrum != null
                    ? (double[])accumulatedReferencePowerSpectrum.Clone()
                    : null;
                frameCount = averagedFrameCount;
                clippedFrames = clippedFrameCount;
                coherenceNoiseFloor = CoherenceNoiseFloor(frameCount, infiniteAveraging, transferAlpha);
            }

            bool micOnly = crossSpectrum == null || referencePowerSpectrum == null;
            double[] magnitude = micOnly
                ? Array.Empty<double>()
                : SpectrumAnalysis.ComputeH1MagnitudeSpectrum(
                    crossSpectrum!,
                    referencePowerSpectrum!);
            // Single-frame gamma^2 is 1 in every energized bin; unknown (null) until a few frames exist. Debiased like the sweep path,
            // against the floor these weights leave. See docs/tech/live-spectrum.md#clipped-frames-and-coherence-bias.
            double[]? coherence = !micOnly && frameCount >= MinCoherenceFrames
                ? SpectrumAnalysis.DebiasCoherence(
                    SpectrumAnalysis.ComputeCoherence(
                        crossSpectrum!,
                        referencePowerSpectrum!,
                        targetPowerSpectrum),
                    coherenceNoiseFloor)
                : null;
            double[]? inputMagnitude = includeInputMagnitude || micOnly
                ? SpectrumAnalysis.ComputeInputMagnitudeSpectrum(
                    targetPowerSpectrum,
                    EffectiveWindowType,
                    SequenceLength)
                : null;
            return new LiveSpectrumSnapshot(
                magnitude, coherence, inputMagnitude, frameCount, clippedFrames);
        }

        /// <summary>What coherence reads on noise alone: the sum of the squared weights the accumulator actually holds. An infinite
        /// mean weighs n frames alike; an exponential one seeds its first frame at weight 1 and decays it, so it reaches the
        /// steady-state α/(2 − α) only after (1 − α)^(2(n−1)) has died away.</summary>
        internal static double CoherenceNoiseFloor(int frameCount, bool infinite, double alpha)
        {
            if (frameCount <= 1)
            {
                return 1.0;
            }
            if (infinite)
            {
                return 1.0 / frameCount;
            }

            double retained = Math.Pow(1.0 - Math.Clamp(alpha, 0.0, 1.0), 2.0 * (frameCount - 1));
            return retained + alpha / (2.0 - alpha) * (1.0 - retained);
        }

        public int ClippedFrameCount
        {
            get
            {
                lock (dataSync)
                {
                    return clippedFrameCount;
                }
            }
        }

        private static double AlphaFromTimeConstant(double frameInterval, double timeConstant)
        {
            if (frameInterval <= 0.0 || timeConstant <= 0.0)
            {
                return 1.0;
            }

            return Math.Clamp(1.0 - Math.Exp(-frameInterval / timeConstant), 1e-6, 1.0);
        }

        private static double GetAveragingTimeConstant(AveragingSpeed speed) => speed switch
        {
            AveragingSpeed.Fast => 0.3,
            AveragingSpeed.Slow => 3.0,
            AveragingSpeed.Infinite => 0.0,
            _ => 1.0
        };

        /// <summary>Restarts the average without stopping capture; UI-thread safe.</summary>
        public void ResetAccumulation()
        {
            lock (dataSync)
            {
                accumulatedCrossSpectrum = null;
                accumulatedReferencePowerSpectrum = null;
                accumulatedTargetPowerSpectrum = null;
                sequencesCounter = 0;
                averagedFrameCount = 0;
                clippedFrameCount = 0;
            }
        }

        public void RefreshLiveAveraging()
        {
            lock (dataSync)
            {
                // Switching averaging speed restarts statistics: the old mode's memory would linger for its whole decay.
                if (EffectiveAveragingSpeed != appliedAveragingSpeed)
                {
                    accumulatedCrossSpectrum = null;
                    accumulatedReferencePowerSpectrum = null;
                    accumulatedTargetPowerSpectrum = null;
                    sequencesCounter = 0;
                    averagedFrameCount = 0;
                    clippedFrameCount = 0;
                }

                UpdateAveragingParameters();
            }
        }

        public bool HasRecentDrops(int windowMilliseconds = 1000)
        {
            long lastDrop = Interlocked.Read(ref lastDropTickMs);
            return inProgress &&
                lastDrop != 0 &&
                Environment.TickCount64 - lastDrop < windowMilliseconds;
        }

        private void OnSequenceDropped(float[][] dropped)
        {
            Interlocked.Increment(ref droppedFrameTotal);
            Interlocked.Exchange(ref lastDropTickMs, Environment.TickCount64);
            Interlocked.Increment(ref dropGeneration);
        }

        private async Task<bool> RunCoreAsync(CancellationToken cancellationToken)
        {
            NoiseSignal noiseSignal = signal!;
            bool success = false;
            var sequenceChannel = Channel.CreateBounded<float[][]>(
                new BoundedChannelOptions(4)
                {
                    SingleReader = true,
                    SingleWriter = true,
                    AllowSynchronousContinuations = false,
                    FullMode = BoundedChannelFullMode.DropOldest
                },
                OnSequenceDropped);
            Volatile.Write(ref sequenceWriter, sequenceChannel.Writer);
            int hopSize = ComputeHopSize();
            lock (dataSync)
            {
                UpdateAveragingParameters();
            }
            // Warm FFT/JIT/allocations before the driver starts, or the first callbacks drop out.
            WarmUpAnalysisPath();

            var reframer = new OverlapReframer(SequenceLength, hopSize);
            Task processingTask = ProcessSequencesAsync(
                sequenceChannel.Reader,
                reframer,
                cancellationToken);

            IAudioStreamingSession? session = null;
            try
            {
                AudioSessionRequest request = BuildSessionRequest();
                AudioPlaybackSignal loopingSignal = new(
                    noiseSignal.FloatData,
                    SampleRate,
                    Bits,
                    PlaybackChannel,
                    Loop: true);
                session = await audioSessionFactory
                    .OpenStreamingAsync(request, cancellationToken).ConfigureAwait(false);
                session.FrameAvailable += HandleFrame;
                session.InputLevelsAvailable += HandleLevels;
                session.CaptureDiscontinuity += HandleCaptureDiscontinuity;
                await session.RunAsync(loopingSignal, SequenceLength, cancellationToken)
                    .ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
                // Cancellation is the normal end of a live capture.
                success = true;
            }
            catch (Exception exception)
            {
                LastError = exception;
            }
            finally
            {
                if (session != null)
                {
                    session.FrameAvailable -= HandleFrame;
                    session.InputLevelsAvailable -= HandleLevels;
                    session.CaptureDiscontinuity -= HandleCaptureDiscontinuity;
                    try
                    {
                        await session.DisposeAsync().ConfigureAwait(false);
                    }
                    catch (Exception exception)
                    {
                        LastError ??= exception;
                    }
                }

                Interlocked.Exchange(ref sequenceWriter, null)?.TryComplete();
                try
                {
                    await processingTask.ConfigureAwait(false);
                }
                catch (OperationCanceledException)
                {
                }
                catch (Exception exception)
                {
                    LastError ??= exception;
                }

                lock (stateSync)
                {
                    inProgress = false;
                }
                try
                {
                    Completed?.Invoke(success);
                }
                catch
                {
                }
            }

            return success;
        }

        // RTA opens the mic alone: WASAPI refuses an endpoint narrower than mic+loopback routing, and ASIO widens the window.
        private AudioSessionRequest BuildSessionRequest() =>
            AudioSessionRequestBuilder.Build(
                AudioBackend,
                SampleRate,
                Bits,
                PlaybackChannel,
                WaveInputChannelOffset,
                IsRtaCapture ? null : WaveLoopbackInputChannelOffset,
                AsioInputChannelOffset,
                IsRtaCapture ? null : AsioLoopbackInputChannelOffset,
                AsioOutputChannelOffset,
                OutputDeviceNumber,
                InputDeviceNumber,
                WasapiCaptureEndpointId,
                WasapiRenderEndpointId,
                AsioDriverName,
                WasapiBufferMilliseconds,
                expectedCaptureSamples: 0);

        private void HandleCaptureDiscontinuity()
        {
            Interlocked.Increment(ref droppedFrameTotal);
            Interlocked.Exchange(ref lastDropTickMs, Environment.TickCount64);
            Interlocked.Increment(ref dropGeneration);
        }

        private void HandleFrame(AudioCaptureFrame frame)
        {
            captureMicrophoneIndex = frame.MicrophoneChannel;
            captureLoopbackIndex = frame.LoopbackChannel ?? -1;
            Volatile.Read(ref sequenceWriter)?.TryWrite(frame.Channels);
        }

        private void HandleLevels(AudioInputLevels levels)
        {
            LevelsAvailable?.Invoke(InputLevelMapping.Map(levels));
        }

        private async Task ProcessSequencesAsync(
            ChannelReader<float[][]> reader,
            OverlapReframer reframer,
            CancellationToken cancellationToken)
        {
            long consumedDropGeneration = Interlocked.Read(ref dropGeneration);
            await foreach (float[][] sequence in reader.ReadAllAsync(cancellationToken).ConfigureAwait(false))
            {
                long generation = Interlocked.Read(ref dropGeneration);
                if (generation != consumedDropGeneration)
                {
                    consumedDropGeneration = generation;
                    reframer.Reset();
                }

                foreach (float[][] frame in reframer.Push(sequence))
                {
                    if (IsRtaCapture)
                    {
                        AccumulateMicOnlySequence(frame);
                    }
                    else
                    {
                        AccumulateTransferSequence(frame);
                    }
                }
            }
        }

        /// <summary>Samples between frames (frame length when overlap is off); frames x hop / rate = integration time.</summary>
        public int AnalysisHopSize => ComputeHopSize();

        private int ComputeHopSize()
        {
            int overlapPercent = Math.Clamp(EffectiveOverlapPercent, 0, 75);
            if (overlapPercent <= 0)
            {
                return SequenceLength;
            }

            int hop = SequenceLength * (100 - overlapPercent) / 100;
            return Math.Clamp(hop, 1, SequenceLength);
        }

        // Periodic pink with a rectangular window: overlapping frames are correlated and add no averaging.
        private int EffectiveOverlapPercent =>
            EffectiveNoiseColor == NoiseColor.PinkPeriodic
                ? 0
                : LiveSpectrumOptions.OverlapPercent;

        private void UpdateAveragingParameters()
        {
            int hopSize = ComputeHopSize();
            double frameInterval = SampleRate > 0 ? (double)hopSize / SampleRate : 0.0;
            AveragingSpeed averaging = EffectiveAveragingSpeed;
            double transferSeconds = GetAveragingTimeConstant(averaging);
            infiniteAveraging = averaging == AveragingSpeed.Infinite;
            transferAlpha = AlphaFromTimeConstant(frameInterval, transferSeconds);
            appliedAveragingSpeed = averaging;
        }

        private void AccumulateTransferSequence(float[][] sequence)
        {
            TransferSpectrumFrame frame = ComputeTransferSpectrumFrame(sequence);
            bool clipped = MicrophoneReachedFullScale(sequence);

            lock (dataSync)
            {
                if (clipped && sequencesCounter > 2)
                {
                    clippedFrameCount++;
                }

                if (accumulatedCrossSpectrum == null ||
                    accumulatedReferencePowerSpectrum == null ||
                    accumulatedTargetPowerSpectrum == null)
                {
                    if (sequencesCounter <= 2)
                    {
                        sequencesCounter++;
                        return;
                    }

                    // Seed with the first frame: the RTA reads sqrt(target power) directly, so a zero seed ramps up from sqrt(alpha) low.
                    accumulatedCrossSpectrum = frame.CrossSpectrum.ToArray();
                    accumulatedReferencePowerSpectrum =
                        frame.ReferencePowerSpectrum.ToArray();
                    accumulatedTargetPowerSpectrum =
                        frame.TargetPowerSpectrum.ToArray();
                    averagedFrameCount = 1;
                    sequencesCounter++;
                    return;
                }

                double alpha = infiniteAveraging
                    ? 1.0 / (averagedFrameCount + 1)
                    : transferAlpha;
                for (int i = 0; i < accumulatedCrossSpectrum.Length; i++)
                {
                    accumulatedCrossSpectrum[i] =
                        (1 - alpha) * accumulatedCrossSpectrum[i] +
                        alpha * frame.CrossSpectrum[i];
                    accumulatedReferencePowerSpectrum[i] =
                        (1 - alpha) * accumulatedReferencePowerSpectrum[i] +
                        alpha * frame.ReferencePowerSpectrum[i];
                    accumulatedTargetPowerSpectrum[i] =
                        (1 - alpha) * accumulatedTargetPowerSpectrum[i] +
                        alpha * frame.TargetPowerSpectrum[i];
                }
                averagedFrameCount++;
                sequencesCounter++;
            }
        }

        // Same settle/seed/EMA as the transfer path; null cross/reference power means mic-only to the snapshot.
        private void AccumulateMicOnlySequence(float[][] sequence)
        {
            int microphoneIndex = captureMicrophoneIndex;
            if ((uint)microphoneIndex >= (uint)sequence.Length)
            {
                throw new InvalidOperationException(
                    "Live RTA requires a microphone input.");
            }

            double[] targetPower = SpectrumAnalysis.ComputeAutoPowerSpectrumFrame(
                sequence[microphoneIndex],
                EffectiveWindowType);
            bool clipped = MicrophoneReachedFullScale(sequence);

            lock (dataSync)
            {
                // Counted exactly when the frame enters the average: the three settling frames are discarded unseen.
                if (clipped && sequencesCounter > 2)
                {
                    clippedFrameCount++;
                }

                if (accumulatedTargetPowerSpectrum == null)
                {
                    if (sequencesCounter <= 2)
                    {
                        sequencesCounter++;
                        return;
                    }

                    accumulatedTargetPowerSpectrum = targetPower;
                    averagedFrameCount = 1;
                    sequencesCounter++;
                    return;
                }

                double alpha = infiniteAveraging
                    ? 1.0 / (averagedFrameCount + 1)
                    : transferAlpha;
                for (int i = 0; i < accumulatedTargetPowerSpectrum.Length; i++)
                {
                    accumulatedTargetPowerSpectrum[i] =
                        (1 - alpha) * accumulatedTargetPowerSpectrum[i] +
                        alpha * targetPower[i];
                }
                averagedFrameCount++;
                sequencesCounter++;
            }
        }

        /// <summary>A clipped frame still enters the average (a walk cannot be repeated), so it is counted and shown instead.</summary>
        private bool MicrophoneReachedFullScale(float[][] sequence)
        {
            int microphoneIndex = captureMicrophoneIndex;
            if ((uint)microphoneIndex >= (uint)sequence.Length)
            {
                return false;
            }

            foreach (float sample in sequence[microphoneIndex])
            {
                if (Math.Abs(sample) >= RecordedLevelMetering.FullScaleThreshold)
                {
                    return true;
                }
            }

            return false;
        }

        private TransferSpectrumFrame ComputeTransferSpectrumFrame(float[][] sequence)
        {
            int microphoneIndex = captureMicrophoneIndex;
            int loopbackIndex = captureLoopbackIndex;
            if (loopbackIndex < 0 ||
                (uint)microphoneIndex >= (uint)sequence.Length ||
                (uint)loopbackIndex >= (uint)sequence.Length)
            {
                throw new InvalidOperationException(
                    "Live transfer function requires a configured loopback input.");
            }

            return SpectrumAnalysis.ComputeTransferSpectrumFrame(
                sequence[loopbackIndex],
                sequence[microphoneIndex],
                EffectiveWindowType);
        }

        private void WarmUpAnalysisPath()
        {
            var reference = new float[SequenceLength];
            var target = new float[SequenceLength];
            reference[0] = 1.0f;
            target[0] = 1.0f;
            TransferSpectrumFrame frame = SpectrumAnalysis.ComputeTransferSpectrumFrame(
                reference,
                target,
                EffectiveWindowType);
            _ = SpectrumAnalysis.ComputeH1MagnitudeSpectrum(
                frame.CrossSpectrum,
                frame.ReferencePowerSpectrum);
            _ = SpectrumAnalysis.ComputeCoherence(
                frame.CrossSpectrum,
                frame.ReferencePowerSpectrum,
                frame.TargetPowerSpectrum);
            _ = SpectrumAnalysis.ComputeInputMagnitudeSpectrum(
                frame.TargetPowerSpectrum,
                EffectiveWindowType,
                SequenceLength);
            _ = SpectrumAnalysis.ComputeAutoPowerSpectrumFrame(target, EffectiveWindowType);
        }

        // Every block holds a whole periodic-pink period, so a rectangular window is leakage-free.
        private WindowType EffectiveWindowType =>
            EffectiveNoiseColor == NoiseColor.PinkPeriodic
                ? WindowType.Rectangular
                : LiveSpectrumOptions.WindowType;

        /// <summary>Colour actually played (MMM pins periodic pink); rule lives on <see cref="LiveSpectrumOptions"/> so the plot agrees.</summary>
        private NoiseColor EffectiveNoiseColor => LiveSpectrumOptions.EffectiveNoiseColor;

        private AveragingSpeed EffectiveAveragingSpeed =>
            LiveSpectrumOptions.EffectiveAveragingSpeed;

        /// <summary>ENBW (bins) of the window actually used, including the periodic-pink rectangular override.</summary>
        public double AnalysisWindowEnbwBins =>
            Windowing.EquivalentNoiseBandwidthBins(EffectiveWindowType, SequenceLength);

        /// <summary>Main-lobe width (bins) of the window actually used, so an integrated RTA band never undercuts it.</summary>
        public double AnalysisWindowMainLobeBins =>
            Windowing.MainLobeWidthBins(EffectiveWindowType);

        /// <summary>Window actually applied (periodic pink forces Rectangular); recipes record this, not the option.</summary>
        public WindowType AnalysisWindowType => EffectiveWindowType;

        private static int? NormalizeOptionalWaveChannel(int? channel) =>
            channel.HasValue
                ? Math.Clamp(channel.Value, 0, 1)
                : null;

        private static int? NormalizeOptionalWasapiChannel(int? channel) =>
            channel.HasValue ? Math.Max(0, channel.Value) : null;

        private void ThrowIfDisposed()
        {
            if (disposed)
            {
                throw new ObjectDisposedException(nameof(NoiseMeasurement));
            }
        }

        public void Dispose()
        {
            if (disposed)
            {
                return;
            }

            disposed = true;
            cancellationTokenSource?.Cancel();
            try
            {
                measurementTask?.GetAwaiter().GetResult();
            }
            catch (OperationCanceledException)
            {
            }
            cancellationTokenSource?.Dispose();
            signal?.Dispose();
            GC.SuppressFinalize(this);
        }
    }
}
